using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FourPlayWebApp.Server.Migrations
{
    /// <inheritdoc />
    public partial class AddNflSeasonWeekConfig : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "NflSeasonWeekConfigs",
                columns: table => new
                {
                    Id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    Season = table.Column<int>(type: "integer", nullable: false),
                    WeekId = table.Column<int>(type: "integer", nullable: false),
                    WeekLabel = table.Column<string>(type: "text", nullable: false),
                    WeekType = table.Column<string>(type: "text", nullable: false),
                    ScoringFormat = table.Column<string>(type: "text", nullable: false),
                    WeekStartDatetime = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                    WeekEndDatetime = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                    FirstGameOfWeekStartDatetime = table.Column<DateTime>(type: "timestamp with time zone", nullable: true),
                    WeekNotes = table.Column<string>(type: "text", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_NflSeasonWeekConfigs", x => x.Id);
                });

            migrationBuilder.CreateIndex(
                name: "IX_NflSeasonWeekConfigs_Season_WeekId",
                table: "NflSeasonWeekConfigs",
                columns: new[] { "Season", "WeekId" },
                unique: true);

            // Seed 2025 and 2026 NFL season schedule from control table spreadsheet
            migrationBuilder.InsertData(
                table: "NflSeasonWeekConfigs",
                columns: new[] { "Season", "WeekId", "WeekLabel", "WeekType", "ScoringFormat",
                                 "WeekStartDatetime", "WeekEndDatetime", "FirstGameOfWeekStartDatetime", "WeekNotes" },
                values: new object[,]
                {
                    // ── 2025 Regular Season (Weeks 1-18) ──────────────────────────────────────
                    { 2025,  1, "Week 1",  "Regular Season", "Standard",
                      new DateTime(2025,  9,  2,  0,  0,  0, DateTimeKind.Utc),
                      new DateTime(2025,  9,  8, 23, 59, 59, DateTimeKind.Utc),
                      new DateTime(2025,  9,  4, 20, 20,  0, DateTimeKind.Utc),
                      "Kickoff Game: DAL at PHI (Thu 8:20p NBC). Int'l game: KC at LAC in Sao Paulo (Fri 8p YouTube). MNF: MIN at CHI Mon Sep 8." },
                    { 2025,  2, "Week 2",  "Regular Season", "Standard",
                      new DateTime(2025,  9,  9,  0,  0,  0, DateTimeKind.Utc),
                      new DateTime(2025,  9, 15, 23, 59, 59, DateTimeKind.Utc),
                      new DateTime(2025,  9, 11, 20, 15,  0, DateTimeKind.Utc),
                      null },
                    { 2025,  3, "Week 3",  "Regular Season", "Standard",
                      new DateTime(2025,  9, 16,  0,  0,  0, DateTimeKind.Utc),
                      new DateTime(2025,  9, 22, 23, 59, 59, DateTimeKind.Utc),
                      new DateTime(2025,  9, 18, 20, 15,  0, DateTimeKind.Utc),
                      "International game (Tottenham, London)." },
                    { 2025,  4, "Week 4",  "Regular Season", "Standard",
                      new DateTime(2025,  9, 23,  0,  0,  0, DateTimeKind.Utc),
                      new DateTime(2025,  9, 29, 23, 59, 59, DateTimeKind.Utc),
                      new DateTime(2025,  9, 25, 20, 15,  0, DateTimeKind.Utc),
                      "International game (London)." },
                    { 2025,  5, "Week 5",  "Regular Season", "Standard",
                      new DateTime(2025,  9, 30,  0,  0,  0, DateTimeKind.Utc),
                      new DateTime(2025, 10,  6, 23, 59, 59, DateTimeKind.Utc),
                      new DateTime(2025, 10,  2, 20, 15,  0, DateTimeKind.Utc),
                      "Bye weeks begin (run through Week 14). International game." },
                    { 2025,  6, "Week 6",  "Regular Season", "Standard",
                      new DateTime(2025, 10,  7,  0,  0,  0, DateTimeKind.Utc),
                      new DateTime(2025, 10, 13, 23, 59, 59, DateTimeKind.Utc),
                      new DateTime(2025, 10,  9, 20, 15,  0, DateTimeKind.Utc),
                      "International game (Tottenham, London)." },
                    { 2025,  7, "Week 7",  "Regular Season", "Standard",
                      new DateTime(2025, 10, 14,  0,  0,  0, DateTimeKind.Utc),
                      new DateTime(2025, 10, 20, 23, 59, 59, DateTimeKind.Utc),
                      new DateTime(2025, 10, 16, 20, 15,  0, DateTimeKind.Utc),
                      "International game (Dublin, Ireland — first-ever NFL game in Ireland)." },
                    { 2025,  8, "Week 8",  "Regular Season", "Standard",
                      new DateTime(2025, 10, 21,  0,  0,  0, DateTimeKind.Utc),
                      new DateTime(2025, 10, 27, 23, 59, 59, DateTimeKind.Utc),
                      new DateTime(2025, 10, 23, 20, 15,  0, DateTimeKind.Utc),
                      "International game (Madrid, Spain — first-ever NFL game in Spain)." },
                    { 2025,  9, "Week 9",  "Regular Season", "Standard",
                      new DateTime(2025, 10, 28,  0,  0,  0, DateTimeKind.Utc),
                      new DateTime(2025, 11,  3, 23, 59, 59, DateTimeKind.Utc),
                      new DateTime(2025, 10, 30, 20, 15,  0, DateTimeKind.Utc),
                      null },
                    { 2025, 10, "Week 10", "Regular Season", "Standard",
                      new DateTime(2025, 11,  4,  0,  0,  0, DateTimeKind.Utc),
                      new DateTime(2025, 11, 10, 23, 59, 59, DateTimeKind.Utc),
                      new DateTime(2025, 11,  6, 20, 15,  0, DateTimeKind.Utc),
                      "International game (Berlin, Germany)." },
                    { 2025, 11, "Week 11", "Regular Season", "Standard",
                      new DateTime(2025, 11, 11,  0,  0,  0, DateTimeKind.Utc),
                      new DateTime(2025, 11, 17, 23, 59, 59, DateTimeKind.Utc),
                      new DateTime(2025, 11, 13, 20, 15,  0, DateTimeKind.Utc),
                      null },
                    { 2025, 12, "Week 12", "Regular Season", "Standard",
                      new DateTime(2025, 11, 18,  0,  0,  0, DateTimeKind.Utc),
                      new DateTime(2025, 11, 24, 23, 59, 59, DateTimeKind.Utc),
                      new DateTime(2025, 11, 20, 20, 15,  0, DateTimeKind.Utc),
                      "TNF Thu Nov 20. Thanksgiving (Thu Nov 27): 3 games (12:30p, 4:30p, 8:20p ET). Black Friday (Fri Nov 28). No byes this week." },
                    { 2025, 13, "Week 13", "Regular Season", "Standard",
                      new DateTime(2025, 12,  2,  0,  0,  0, DateTimeKind.Utc),
                      new DateTime(2025, 12,  8, 23, 59, 59, DateTimeKind.Utc),
                      new DateTime(2025, 12,  4, 20, 15,  0, DateTimeKind.Utc),
                      null },
                    { 2025, 14, "Week 14", "Regular Season", "Standard",
                      new DateTime(2025, 12,  9,  0,  0,  0, DateTimeKind.Utc),
                      new DateTime(2025, 12, 15, 23, 59, 59, DateTimeKind.Utc),
                      new DateTime(2025, 12, 11, 20, 15,  0, DateTimeKind.Utc),
                      "Last week byes can occur (byes end Week 14)." },
                    { 2025, 15, "Week 15", "Regular Season", "Standard",
                      new DateTime(2025, 12, 16,  0,  0,  0, DateTimeKind.Utc),
                      new DateTime(2025, 12, 22, 23, 59, 59, DateTimeKind.Utc),
                      new DateTime(2025, 12, 18, 20, 15,  0, DateTimeKind.Utc),
                      null },
                    { 2025, 16, "Week 16", "Regular Season", "Standard",
                      new DateTime(2025, 12, 23,  0,  0,  0, DateTimeKind.Utc),
                      new DateTime(2025, 12, 29, 23, 59, 59, DateTimeKind.Utc),
                      new DateTime(2025, 12, 25, 13,  0,  0, DateTimeKind.Utc),
                      "Christmas Day (Thu 12/25): DAL at WAS, DET at MIN (afternoon), DEN at KC (TNF 8:15p). Saturday games also this week." },
                    { 2025, 17, "Week 17", "Regular Season", "Standard",
                      new DateTime(2025, 12, 30,  0,  0,  0, DateTimeKind.Utc),
                      new DateTime(2026,  1,  5, 23, 59, 59, DateTimeKind.Utc),
                      new DateTime(2026,  1,  1, 20, 15,  0, DateTimeKind.Utc),
                      "New Year's Day TNF opener (Thu Jan 1). Saturday games included. NOTE: Jan 3-4 W18 games fall within this boundary window — see Week 18 note." },
                    { 2025, 18, "Week 18", "Regular Season", "Standard",
                      new DateTime(2026,  1,  6,  0,  0,  0, DateTimeKind.Utc),
                      new DateTime(2026,  1, 12, 23, 59, 59, DateTimeKind.Utc),
                      new DateTime(2026,  1,  3, 16, 30,  0, DateTimeKind.Utc),
                      "All 16 games are division matchups. Games played Sat Jan 3 (2 games: 4:30p & 8p ESPN/ABC) and Sun Jan 4 — before this boundary opens. first_game_datetime reflects actual kickoff. No MNF." },
                    // ── 2025 Postseason ───────────────────────────────────────────────────────
                    { 2025, 19, "Wild Card Weekend",      "Wild Card",             "NFL Dvisional",
                      new DateTime(2026,  1,  6,  0,  0,  0, DateTimeKind.Utc),
                      new DateTime(2026,  1, 12, 23, 59, 59, DateTimeKind.Utc),
                      new DateTime(2026,  1, 10, 13,  0,  0, DateTimeKind.Utc),
                      "6 games: Sat Jan 10, Sun Jan 11, Mon Jan 12. No. 1 seed in each conf receives bye. Broadcast across CBS, Fox, NBC, ESPN/ABC, Prime Video." },
                    { 2025, 20, "Divisional Round",       "Divisional",            "NFL Dvisional",
                      new DateTime(2026,  1, 13,  0,  0,  0, DateTimeKind.Utc),
                      new DateTime(2026,  1, 19, 23, 59, 59, DateTimeKind.Utc),
                      new DateTime(2026,  1, 17, 16, 30,  0, DateTimeKind.Utc),
                      "4 games: Sat Jan 17 (BUF vs DEN 4:30p CBS, SF vs SEA 8:20p FOX), Sun Jan 18 (HOU vs NE 3p ESPN/ABC, LAR vs CHI 6:30p NBC)." },
                    { 2025, 21, "Conference Championships","Conference Championship","NFL Conference Championship",
                      new DateTime(2026,  1, 20,  0,  0,  0, DateTimeKind.Utc),
                      new DateTime(2026,  1, 26, 23, 59, 59, DateTimeKind.Utc),
                      new DateTime(2026,  1, 25, 15,  0,  0, DateTimeKind.Utc),
                      "AFC Championship: NE vs DEN 3p CBS/Paramount+. NFC Championship: LAR vs SEA 6:30p FOX. Sun Jan 25. SEA and NE advance to Super Bowl LX." },
                    { 2025, 22, "Super Bowl LX",           "Super Bowl",            "NFL Super Bowl",
                      new DateTime(2026,  2,  3,  0,  0,  0, DateTimeKind.Utc),
                      new DateTime(2026,  2,  9, 23, 59, 59, DateTimeKind.Utc),
                      new DateTime(2026,  2,  8, 18, 30,  0, DateTimeKind.Utc),
                      "Super Bowl LX at Levi's Stadium, Santa Clara, CA. NBC/Peacock. SEA defeated NE 29-13. Kenneth Walker III named Super Bowl MVP." },

                    // ── 2026 Regular Season (Weeks 1-18) ──────────────────────────────────────
                    { 2026,  1, "Week 1",  "Regular Season", "Standard",
                      new DateTime(2026,  9,  8,  0,  0,  0, DateTimeKind.Utc),
                      new DateTime(2026,  9, 14, 23, 59, 59, DateTimeKind.Utc),
                      new DateTime(2026,  9,  9, 20, 20,  0, DateTimeKind.Utc),
                      "Opener: NE at SEA (Wed 8:20p NBC). First-ever NFL game in Australia: SF vs LAR in Melbourne (Thu 8:35p Netflix). MNF: DEN at KC Mon Sep 14." },
                    { 2026,  2, "Week 2",  "Regular Season", "Standard",
                      new DateTime(2026,  9, 15,  0,  0,  0, DateTimeKind.Utc),
                      new DateTime(2026,  9, 21, 23, 59, 59, DateTimeKind.Utc),
                      new DateTime(2026,  9, 17, 20, 15,  0, DateTimeKind.Utc),
                      "First TNF of season. DET at BUF — first regular-season game at new Highmark Stadium." },
                    { 2026,  3, "Week 3",  "Regular Season", "Standard",
                      new DateTime(2026,  9, 22,  0,  0,  0, DateTimeKind.Utc),
                      new DateTime(2026,  9, 28, 23, 59, 59, DateTimeKind.Utc),
                      new DateTime(2026,  9, 24, 20, 15,  0, DateTimeKind.Utc),
                      null },
                    { 2026,  4, "Week 4",  "Regular Season", "Standard",
                      new DateTime(2026,  9, 29,  0,  0,  0, DateTimeKind.Utc),
                      new DateTime(2026, 10,  5, 23, 59, 59, DateTimeKind.Utc),
                      new DateTime(2026, 10,  1, 20, 15,  0, DateTimeKind.Utc),
                      null },
                    { 2026,  5, "Week 5",  "Regular Season", "Standard",
                      new DateTime(2026, 10,  6,  0,  0,  0, DateTimeKind.Utc),
                      new DateTime(2026, 10, 12, 23, 59, 59, DateTimeKind.Utc),
                      new DateTime(2026, 10,  8, 20, 15,  0, DateTimeKind.Utc),
                      "Bye weeks begin (run through Week 14). International game." },
                    { 2026,  6, "Week 6",  "Regular Season", "Standard",
                      new DateTime(2026, 10, 13,  0,  0,  0, DateTimeKind.Utc),
                      new DateTime(2026, 10, 19, 23, 59, 59, DateTimeKind.Utc),
                      new DateTime(2026, 10, 15, 20, 15,  0, DateTimeKind.Utc),
                      "International game (London)." },
                    { 2026,  7, "Week 7",  "Regular Season", "Standard",
                      new DateTime(2026, 10, 20,  0,  0,  0, DateTimeKind.Utc),
                      new DateTime(2026, 10, 26, 23, 59, 59, DateTimeKind.Utc),
                      new DateTime(2026, 10, 22, 20, 15,  0, DateTimeKind.Utc),
                      "International game (London)." },
                    { 2026,  8, "Week 8",  "Regular Season", "Standard",
                      new DateTime(2026, 10, 27,  0,  0,  0, DateTimeKind.Utc),
                      new DateTime(2026, 11,  2, 23, 59, 59, DateTimeKind.Utc),
                      new DateTime(2026, 10, 29, 20, 15,  0, DateTimeKind.Utc),
                      "International game (Rio de Janeiro, Brazil)." },
                    { 2026,  9, "Week 9",  "Regular Season", "Standard",
                      new DateTime(2026, 11,  3,  0,  0,  0, DateTimeKind.Utc),
                      new DateTime(2026, 11,  9, 23, 59, 59, DateTimeKind.Utc),
                      new DateTime(2026, 11,  5, 20, 15,  0, DateTimeKind.Utc),
                      null },
                    { 2026, 10, "Week 10", "Regular Season", "Standard",
                      new DateTime(2026, 11, 10,  0,  0,  0, DateTimeKind.Utc),
                      new DateTime(2026, 11, 16, 23, 59, 59, DateTimeKind.Utc),
                      new DateTime(2026, 11, 12, 20, 15,  0, DateTimeKind.Utc),
                      "International game (Paris, Stade de France)." },
                    { 2026, 11, "Week 11", "Regular Season", "Standard",
                      new DateTime(2026, 11, 17,  0,  0,  0, DateTimeKind.Utc),
                      new DateTime(2026, 11, 23, 23, 59, 59, DateTimeKind.Utc),
                      new DateTime(2026, 11, 19, 20, 15,  0, DateTimeKind.Utc),
                      "International game (Madrid, Bernabeu Stadium). Last normal week before Thanksgiving stretch." },
                    { 2026, 12, "Week 12", "Regular Season", "Standard",
                      new DateTime(2026, 11, 24,  0,  0,  0, DateTimeKind.Utc),
                      new DateTime(2026, 11, 30, 23, 59, 59, DateTimeKind.Utc),
                      new DateTime(2026, 11, 25, 20,  0,  0, DateTimeKind.Utc),
                      "Thanksgiving Eve (Wed 11/25): GB at LAR 8p Netflix. Thanksgiving (Thu 11/26): CHI at DET 1p CBS, PHI at DAL 4:30p FOX, KC at BUF 8:20p NBC. Black Friday (Fri 11/27): DEN at PIT 3p Prime Video. No byes this week." },
                    { 2026, 13, "Week 13", "Regular Season", "Standard",
                      new DateTime(2026, 12,  1,  0,  0,  0, DateTimeKind.Utc),
                      new DateTime(2026, 12,  7, 23, 59, 59, DateTimeKind.Utc),
                      new DateTime(2026, 12,  3, 20, 15,  0, DateTimeKind.Utc),
                      "International game (Munich, FC Bayern Arena)." },
                    { 2026, 14, "Week 14", "Regular Season", "Standard",
                      new DateTime(2026, 12,  8,  0,  0,  0, DateTimeKind.Utc),
                      new DateTime(2026, 12, 14, 23, 59, 59, DateTimeKind.Utc),
                      new DateTime(2026, 12, 10, 20, 15,  0, DateTimeKind.Utc),
                      "Last week byes can occur. International game (Mexico City, Estadio Banorte)." },
                    { 2026, 15, "Week 15", "Regular Season", "Standard",
                      new DateTime(2026, 12, 15,  0,  0,  0, DateTimeKind.Utc),
                      new DateTime(2026, 12, 21, 23, 59, 59, DateTimeKind.Utc),
                      new DateTime(2026, 12, 17, 20, 15,  0, DateTimeKind.Utc),
                      "Saturday games begin (Weeks 15-17 may include Saturday matchups per flexible scheduling)." },
                    { 2026, 16, "Week 16", "Regular Season", "Standard",
                      new DateTime(2026, 12, 22,  0,  0,  0, DateTimeKind.Utc),
                      new DateTime(2026, 12, 28, 23, 59, 59, DateTimeKind.Utc),
                      new DateTime(2026, 12, 25, 13,  0,  0, DateTimeKind.Utc),
                      "Christmas Day (Fri 12/25): GB at CHI 1p Netflix, BUF at DEN 4:30p Netflix, LAR at SEA 8:15p FOX. Two Sat games (4:30p NFL Network & 8p NFL Network) TBD." },
                    { 2026, 17, "Week 17", "Regular Season", "Standard",
                      new DateTime(2026, 12, 29,  0,  0,  0, DateTimeKind.Utc),
                      new DateTime(2027,  1,  4, 23, 59, 59, DateTimeKind.Utc),
                      new DateTime(2027,  1,  1, 20, 15,  0, DateTimeKind.Utc),
                      "New Year's Day TNF opener. Two Saturday games (Sat 4:30p NBC, Sat 8p Peacock) TBD. Matchups announced after Week 15." },
                    { 2026, 18, "Week 18", "Regular Season", "Standard",
                      new DateTime(2027,  1,  5,  0,  0,  0, DateTimeKind.Utc),
                      new DateTime(2027,  1, 11, 23, 59, 59, DateTimeKind.Utc),
                      new DateTime(2027,  1,  9, 13,  0,  0, DateTimeKind.Utc),
                      "All 16 games are division matchups. Sat Jan 9: 3 games (1p Netflix, 4:30p ESPN/ABC, 8p ESPN/ABC). Sun Jan 10: remainder. Matchups announced after Week 17." },
                    // ── 2026 Postseason ───────────────────────────────────────────────────────
                    { 2026, 19, "Wild Card Weekend",       "Wild Card",             "NFL Dvisional",
                      new DateTime(2027,  1, 13,  0,  0,  0, DateTimeKind.Utc),
                      new DateTime(2027,  1, 19, 23, 59, 59, DateTimeKind.Utc),
                      new DateTime(2027,  1, 16, 13,  0,  0, DateTimeKind.Utc),
                      "6 games: Sat Jan 16, Sun Jan 17, Mon Jan 18. No. 1 seed in each conf receives bye. Games distributed Sat-Mon across CBS, Fox, NBC, ESPN/ABC, Prime Video." },
                    { 2026, 20, "Divisional Round",        "Divisional",            "NFL Dvisional",
                      new DateTime(2027,  1, 20,  0,  0,  0, DateTimeKind.Utc),
                      new DateTime(2027,  1, 26, 23, 59, 59, DateTimeKind.Utc),
                      new DateTime(2027,  1, 23, 13,  0,  0, DateTimeKind.Utc),
                      "4 games across Sat Jan 23 and Sun Jan 24. Top seeds enter. Higher seed hosts." },
                    { 2026, 21, "Conference Championships","Conference Championship","NFL Conference Championship",
                      new DateTime(2027,  1, 27,  0,  0,  0, DateTimeKind.Utc),
                      new DateTime(2027,  2,  2, 23, 59, 59, DateTimeKind.Utc),
                      new DateTime(2027,  1, 31, 15,  0,  0, DateTimeKind.Utc),
                      "AFC Championship (~3p ET) and NFC Championship (~6:30p ET) on Sun Jan 31. Broadcast on CBS (AFC) and FOX (NFC)." },
                    { 2026, 22, "Super Bowl LXI",          "Super Bowl",            "NFL Super Bowl",
                      new DateTime(2027,  2, 10,  0,  0,  0, DateTimeKind.Utc),
                      new DateTime(2027,  2, 15, 23, 59, 59, DateTimeKind.Utc),
                      new DateTime(2027,  2, 14, 18, 30,  0, DateTimeKind.Utc),
                      "Super Bowl LXI at SoFi Stadium, Inglewood, CA. Broadcast on ESPN & ABC. First Super Bowl on Valentine's Day." },
                });
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "NflSeasonWeekConfigs");
        }
    }
}
